# Remember, leave a key empty if there is no value.  None will be a string,
# not a Python "NoneType"
client:
  hosts: [ "x1.x1.x1.x1","x2.x2.x2.x2" ]
  port: 9200
  timeout: 30

logging:
  loglevel: INFO
