## see https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
#
cluster.name: Docker-Cluster
node.name: elasticsearch01
network.bind_host: 0.0.0.0
network.publish_host: x1.x1.x1.x1
discovery.zen.minimum_master_nodes: 2
discovery.zen.ping.unicast.hosts: ["x1.x1.x1.x1","x2.x2.x2.x2"]

## Disable X-Pack
## see https://www.elastic.co/guide/en/x-pack/current/xpack-settings.html
##     https://www.elastic.co/guide/en/x-pack/current/installing-xpack.html#xpack-enabling
#
xpack.security.enabled: false
xpack.monitoring.enabled: false
xpack.ml.enabled: false
xpack.graph.enabled: false
xpack.watcher.enabled: false
